<a href="https://colab.research.google.com/github/sadafquraishi/mypracticerepository/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
import time 
from sys import getsizeof

In [5]:
import array as arr

numbers_list = [2, 5, 62, 5, 42, 52, 48, 5]
numbers_array = arr.array('i', numbers_list)

print(numbers_array[2:5]) # 3rd to 5th
print(numbers_array[:-5]) # beginning to 4th
print(numbers_array[5:])  # 6th to end
print(numbers_array[:])   # beginning to end

array('i', [62, 5, 42])
array('i', [2, 5, 62])
array('i', [52, 48, 5])
array('i', [2, 5, 62, 5, 42, 52, 48, 5])


In [0]:
arr_1=np.arange(60).reshape(3,4,5)

In [7]:
arr_1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [13]:
arr_1[0:2, 1:2, 1:3] # 0:2 gives first 2 matrices, 1:2 gives rows, 1:3 gives columns

array([[[ 6,  7]],

       [[26, 27]]])

In [18]:
np.linspace(0,10,4)

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [0]:
arr_1=np.arange(30)

In [40]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [0]:
array_1=arr_1.reshape(3,10)

In [29]:
array_1.ndim

2

In [30]:
array_1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [0]:
arr_1=np.arange(30)

In [32]:
arr_1.shape

(30,)

In [0]:
arr_2= arr_1.reshape(-1,1)

In [37]:
arr_2.shape

(30, 1)

In [38]:
arr_2

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25],
       [26],
       [27],
       [28],
       [29]])

In [0]:
arr_2=np.arange(40)

In [42]:
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [47]:
arr_2[(arr_2>20) & (arr_2<30)] #filtering example

array([21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
arr_2[(arr_2%2==0)&(arr_2%3==0)] #filtering example

array([ 0,  6, 12, 18, 24, 30, 36])

In [49]:
arr_2[(arr_2%2==0)|(arr_2%3==0)] #filtering example

array([ 0,  2,  3,  4,  6,  8,  9, 10, 12, 14, 15, 16, 18, 20, 21, 22, 24,
       26, 27, 28, 30, 32, 33, 34, 36, 38, 39])

In [50]:
arr_2[~((arr_2%2==0)|(arr_2%3==0))] #filtering example

array([ 1,  5,  7, 11, 13, 17, 19, 23, 25, 29, 31, 35, 37])

In [51]:
arr_2[~((arr_2%2==0)&(arr_2%3==0))] #filtering example

array([ 1,  2,  3,  4,  5,  7,  8,  9, 10, 11, 13, 14, 15, 16, 17, 19, 20,
       21, 22, 23, 25, 26, 27, 28, 29, 31, 32, 33, 34, 35, 37, 38, 39])

In [0]:
import numpy as np
import pandas as pd
import csv

In [0]:
path= "KAG_conversion_data.csv"
with open(path) as f:
  adm=csv.reader(f,delimiter= ",")
  adm=list(adm)
adm.remove(adm[0])

In [0]:
sales_data=np.array(adm)

In [65]:
sales_data.shape

(1143, 11)

In [0]:
unique_campaigns = np.unique(sales_data[:,1]) #unique campaigns

In [91]:
print(unique_campaigns)

['1178' '916' '936']


In [0]:
campaign_count=np.unique(sales_data[:,1], return_counts=True) #campaign count

In [95]:
print(campaign_count)

(array(['1178', '916', '936'], dtype='<U11'), array([625,  54, 464]))


In [0]:
age_group= np.unique(sales_data[:,3]) #targeted age group

In [97]:
print(age_group)

['30-34' '35-39' '40-44' '45-49']


In [0]:
max_spent= np.unique(sales_data[:,8].astype(float).max()) #max ad spend

In [0]:
min_spent= np.unique(sales_data[:,8].astype(float).min()) #min ad spend

In [0]:
avg_spent= np.unique(sales_data[:,8].astype(float).mean()) #avg ad spend

In [110]:
print(max_spent)
print(min_spent)
print(avg_spent)

[639.9499981]
[0.]
[51.36065613]


In [0]:
max_clicks= np.unique(sales_data[:,7].astype(float).max()) #max clicks

In [115]:
print(max_clicks)

[421.]


In [0]:
# Code starts here
import numpy as np
# initialize matrix A and b
A = np.array([[2,1,2], [3,0,1], [1,1,-1]])
b = np.array([-3, 5, 2])

# Solve for x
x = np.linalg.solve(A, b)

# Check solution
check = np.allclose(np.dot(A,x), b)


# Code ends here

In [123]:
print(x)

[ 2.5 -3.  -2.5]
