<a href="https://colab.research.google.com/github/sadafquraishi/mypracticerepository/blob/master/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
age=20
sentence = "My name is Sadaf"

In [0]:
sentence

'My name is Sadaf'

In [0]:
sarah, bob, mike=16,21,17

In [0]:
sarah

16

In [0]:
sarah=bob=mike=17

In [0]:
bob

17

In [0]:
age, name= 21,"My name is Sadaf"

In [0]:
age

21

In [0]:
name

'My name is Sadaf'

In [0]:
age1, age2= 12, 18

In [0]:
age1+age2

30

In [0]:
age1-age2

-6

In [0]:
age1/age2

0.6666666666666666

In [0]:
age1*age2

216

In [0]:
age1%age2

12

In [0]:
sentence1="Today was a beautiful day"

In [0]:
firstname="Sadaf"

In [0]:
lastname="Quraishi"

In [0]:
firstname+ " "+lastname

'Sadaf Quraishi'

In [0]:
firstname*2

'SadafSadaf'

In [0]:
sent2="Sadaf was playing basketball"

In [0]:
sent2[0:5]

'Sadaf'

In [0]:
sent2[0:12]

'Sadaf was pl'

In [0]:
name= "Jake"

In [0]:
name + " is 15 years old"

'Jake is 15 years old'

In [0]:
sent= "%s is 15 years old"

In [0]:
sent%name

'Jake is 15 years old'

In [0]:
sent%"Sadaf"

'Sadaf is 15 years old'

In [0]:
sent%("Sadaf")

'Sadaf is 15 years old'

In [0]:
sent= "%s %s is the President of US"

In [0]:
sent%("Barak", "Obama")

'Barak Obama is the President of US'

In [0]:
sent= "%s is %d years old"

In [0]:
sent%("barak", 50)

'barak is 50 years old'

In [0]:
sent2=sent%("Barak", 50)

In [0]:
sent2

'Barak is 50 years old'

In [0]:
shoplist=["apples","oranges","banana","cheese"]

In [0]:
shoplist

['apples', 'oranges', 'banana', 'cheese']

In [0]:
shoplist[0]

'apples'

In [0]:
shoplist[3]

'cheese'

In [0]:
shoplist[0:2]

['apples', 'oranges']

In [0]:
shoplist.append("blueberries")

In [0]:
shoplist

['apples', 'oranges', 'banana', 'cheese', 'blueberries']

In [0]:
shoplist[0]="cherries"

In [0]:
shoplist

['cherries', 'oranges', 'banana', 'cheese', 'blueberries']

In [0]:
del shoplist[1]

In [0]:
shoplist

['cherries', 'banana', 'cheese', 'blueberries']

In [0]:
len(shoplist)

4

In [0]:
shoplist2=["bread","jam","peanut butter"]

In [0]:
shoplist + shoplist2

['cherries',
 'banana',
 'cheese',
 'blueberries',
 'bread',
 'jam',
 'peanut butter']

In [0]:
shoplist*2

['cherries',
 'banana',
 'cheese',
 'blueberries',
 'cherries',
 'banana',
 'cheese',
 'blueberries']

In [0]:
listnum=(1,2,3,5)

In [0]:
max(listnum)

5

In [0]:
min(listnum)

1

In [0]:
students={"bob":12, "rachel":13, "emily":15}

In [0]:
students

{'bob': 12, 'emily': 15, 'rachel': 13}

In [0]:
students["rachel"]

13

In [0]:
students["rachel"]=15

In [0]:
students

{'bob': 12, 'emily': 15, 'rachel': 15}

In [0]:
del students["emily"]

In [0]:
students

{'bob': 12, 'rachel': 15}

In [0]:
len(students)

2

In [0]:
tup=('oranges', 'apples', 'bananas')

In [0]:
tup

('oranges', 'apples', 'bananas')

In [0]:
tup[0]

'oranges'

In [0]:
tup[0:3]

('oranges', 'apples', 'bananas')

In [0]:
tup1=(12,14)

In [0]:
tup2=tup+tup1

In [0]:
tup2

('oranges', 'apples', 'bananas', 12, 14)

In [0]:
del tup2

In [0]:
len(tup)

3

In [0]:
tup*2

('oranges', 'apples', 'bananas', 'oranges', 'apples', 'bananas')

In [0]:
if (5>3):
  print("hello")

hello


In [0]:
if(3<2):
  print("hello")
else:
 print("not true")

not true


In [0]:
3>=2

True

In [0]:
3 !=2

True

In [0]:
if (age<13):
  print("you are a teen")
elif (age >= 13 and age<18):
  print("you are a teen")
else:
  print("You are an adult")

You are an adult


In [0]:
age=21

In [0]:
if (age<13):
  print("you are a teen")
elif (age >= 13 and age<18):
  print("you are a teen")
else:
  print("You are an adult")

You are an adult


In [0]:
if (5>3 and 2<11):
  print("hi")

hi


In [0]:
if (5>3 or 2<11):
  print("uwu")

uwu


In [0]:
list1=["apples", "bananas","cherries"]

In [0]:
tup1=(13,12,15)

In [0]:
for item in list1:
  print(item)

apples
bananas
cherries


In [0]:
for item in tup1:
  print(item)

13
12
15


In [0]:
for i in range(0,10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [0]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [0]:
for i in range(0,11,2):
  print(i)

0
2
4
6
8
10


In [0]:
for i in range(1,11,2):
  print(i)

1
3
5
7
9


In [0]:
for i in range(0,5):
  for j in range(0,3):
    print(i*j)

0
0
0
0
1
2
0
2
4
0
3
6
0
4
8


In [0]:
c=0

In [0]:
while c<5:
  print(c)
  c=c+1
  

0
1
2
3
4


In [0]:
c=0

In [0]:
while c<5:
  print(c)
  if c==3:
    break
  c=c+1

0
1
2
3


In [0]:
c=0
while c<5:
  print(c)
  c=c+1

0
1
2
3
4


In [0]:
c=0
while c<5:
  print(c)
  if c==3:
   break
  c=c+1

0
1
2
3


In [0]:
try:
  if name>3:
    print("Hello")
except:
  print("Wrong Code")

Wrong Code


In [0]:
try:
  if name>100:
    print("Hi")
except:
  print("wrong code")

wrong code


In [0]:
def Helloworld():
  print("Hello World")

In [0]:
Helloworld()

Hello World


In [0]:
def greeting(name):
  print("Hi" +" "+ name+"!")

In [0]:
greeting("Sadaf")

Hi Sadaf!


In [0]:
def Add(num1,num2):
  return(num1+num2)
  print("Hello")

In [0]:
plus=Add(10,15)

In [0]:
print(plus)

25


In [0]:
number = 5
count = 0
while number > 1: 
    number = number / 2
    count  += 1  

print(count)

3


In [0]:
multiples= []
for i in range(0,100):
    if i%3:
        continue
    else:
        multiples.append(i)
print(multiples)

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [0]:
rating=4

if rating>4:
    print('Great movie')
elif rating>2:
    print('Good movie')
else: 
    print('Bad movie')

Good movie


In [0]:
for i in range(1,5):
    print('Wow')

Wow
Wow
Wow
Wow


In [0]:
print("abra","kadabra" ,sep='**')


abra**kadabra


In [0]:

num1, num2 = 5, 0
try:
    quotient = (num1/num2)
    message= "Quotient is" + ' ' + str(quotient)
    print(message)
    
except:
    message= "ZeroDivisionError"
    print(message)

ZeroDivisionError


In [0]:
try:
    a = 0 / 1
    message = "Quotient is" + ' ' + str(a)
    print(message)
except ZeroDivisionError:
    message = "Cannot divide zero"
    print(message)

Quotient is 0.0


In [0]:
def func():

    return("12")

def func():

    return("13")

print(func()) 

13


In [0]:
nums = [1,2,3,4,5]
func = lambda x: (x*2)
output = list(map(func, nums))
print(output)

[2, 4, 6, 8, 10]


In [0]:
global a

a=2

def func():
    a=1
    b=2
    return (a+b)

print(func())

3


In [1]:
import numpy as np

# Code starts here
def der(x,a=None):
    res= (x**2)*(a*x)
    return res

sol=(der(1,2))
print(sol)

2


In [2]:

# Function to find derivative
def der1(x=None):
    res = np.exp(x) + x*np.exp(x)
    return res

# Calling the function for x=1
print(der1(1))

5.43656365691809


In [3]:
# Code starts here
def der(x,a=None):
    res= (x**2)*(a**x)
    return res

sol=(der(1,2))
print(sol)

# Code ends here

2


In [4]:
import numpy as np
# Code starts here

# initialize NumPy array
array=np.arange(1,11)

# check dimensions
dim= print('The dimensions of array is ', array.ndim)

# reshaped array
reshaped=np.arange(1,11).reshape((5,2))

# check shape
new_dim=print('The dimensions of array a is ', reshaped.ndim)
# Code ends here

The dimensions of array is  1
The dimensions of array a is  2


In [5]:
# NumPy array from 1 to 19
print(np.arange(1,20,dtype='int32'))

# NumPy array from 1 to 19 with step size 2
print(np.arange(1,20,2,dtype='int8'))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [6]:
print( np.arange(5))

[0 1 2 3 4]


In [7]:
import numpy as np
print(np.eye(5))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a[1,1])

4


In [9]:
a = np.array([[4,7,1],[2,5,7],[7,1,1]])

# Boolean condition for values greater than 3
mask = a > 3
print(mask)

# Masking for the above boolean condition in the array
print(a[mask])

[[ True  True False]
 [False  True  True]
 [ True False False]]
[4 7 5 7 7]


In [10]:
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print(a[a > 2])

[3 4 5 6 7]


In [11]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[10,11,12],[13,14,15],[16,17,18]])

# element wise addition
print(a+b)
print('==========')
print(np.add(a,b))

[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]


In [12]:
a = np.array([[1,4,9],[16,25,36]])
print(np.log(a))

[[0.         1.38629436 2.19722458]
 [2.77258872 3.21887582 3.58351894]]
